# Generated by Django 6.1 on 2026-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_commentary_content_alter_commentary_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
